repos:
  # Basic built in into pre-commit linters (validate json, xml, yaml and toml syntax, ensure no merge conflicts and no trailing whitespaces)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-xml
        stages: [commit]
      - id: check-yaml
        stages: [commit]
        args: [--unsafe]
      - id: check-toml
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: name-tests-test
        stages: [commit]
        args: ['--django']
      - id: no-commit-to-branch
        stages: [commit]
      - id: mixed-line-ending
        stages: [commit]
      - id: requirements-txt-fixer
        stages: [commit]
      - id: trailing-whitespace
        stages: [commit]
        args: [--markdown-linebreak-ext=md]

  # Remove unused imports
  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        stages: [commit]
        args:
          [
            '--in-place',
            '--remove-all-unused-imports',
            '--ignore-init-module-imports',
            '--recursive',
          ]

  # Autoformats python code to a single standard
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        stages: [commit]
        args: ['--line-length=99']

  # Groups and sorts python imports, see .isort.cfg for configuration
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        stages: [commit]

  # Markdown linter, see markdownlint.yaml for configuration
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.35.0
    hooks:
      - id: markdownlint
        stages: [commit]
        args: ['--fix']

  # - repo: local
  #   hooks:
  #     - id: pytest
  #       name: pytest
  #       entry: /opt/conda/bin/pytest
  #       language: script
  #       pass_filenames: false
  #       always_run: true

  # Push hooks (runs on push because developers may commit incomplete changes)
  # Python files linter, see .pylintrc for configuration
  - repo: https://github.com/PyCQA/pylint
    rev: v3.0.0a6
    hooks:
      - id: pylint
        stages: [push]

  # Python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        stages: [push]

fail_fast: true
